In [2]:
# import matplotlib.pyplot as plt
import plotly.graph_objects as go
import pandas as pd 
from utils import *

2025-02-16 08:34:13.270 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-02-16 08:34:13.290 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [14]:
sql_link = """
with link_l_r as (
	SELECT 
		'L-R' as "link", 2 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_left, '')) <> '' 
	AND TRIM(COALESCE(zi_right, '')) <> '' 
	AND TRIM(COALESCE(zi_up,zi_down,zi_mid,zi_left_up, zi_left_down,zi_right_up,zi_right_down,zi_mid_in,zi_mid_out,'')) = '' 
)

, link_l_m as (
	SELECT 
		'L-M' as "link", 2 as "bodies",t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_left, '')) <> '' 
	AND TRIM(COALESCE(zi_mid, '')) <> '' 
	AND TRIM(COALESCE(zi_up,zi_down,zi_right,zi_left_up, zi_left_down,zi_right_up,zi_right_down,zi_mid_in,zi_mid_out,'')) = '' 
)
, link_m_r as (
SELECT 
		'M-R' as "link", 2 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_mid, '')) <> '' 
	AND TRIM(COALESCE(zi_right, '')) <> '' 
	AND TRIM(COALESCE(zi_up,zi_down,zi_left,zi_left_up, zi_left_down,zi_right_up,zi_right_down,zi_mid_in,zi_mid_out,'')) = '' 
)
, link_l_m_r as (
	SELECT 
		'L-M-R' as "link", 3 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_left, '')) <> '' 
	AND TRIM(COALESCE(zi_mid, '')) <> '' 
	AND TRIM(COALESCE(zi_right, '')) <> '' 
	AND TRIM(COALESCE(zi_up,zi_down,zi_left_up, zi_left_down,zi_right_up,zi_right_down,zi_mid_in,zi_mid_out,'')) = '' 
)
, link_l_m_r_d as (
	SELECT 
		'L-M-R-D' as "link", 4 as "bodies",  t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_left, '')) <> '' 
	AND TRIM(COALESCE(zi_mid, '')) <> '' 
	AND TRIM(COALESCE(zi_right, '')) <> '' 
	AND TRIM(COALESCE(zi_down, '')) <> '' 
	AND TRIM(COALESCE(zi_up,zi_left_up, zi_left_down,zi_right_up,zi_right_down,zi_mid_in,zi_mid_out,'')) = '' 
)
, link_u_d as (
	SELECT 
		'U-D' as "link", 2 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_up , '')) <> '' 
	AND TRIM(COALESCE(zi_down , '')) <> '' 
	AND TRIM(COALESCE(zi_left,zi_right,zi_mid,zi_left_up, zi_left_down,zi_right_up,zi_right_down,zi_mid_in,zi_mid_out,'')) = '' 
)
, link_u_m as (
	SELECT 
		'U-M' as "link", 2 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_up , '')) <> '' 
	AND TRIM(COALESCE(zi_mid  , '')) <> '' 
	AND TRIM(COALESCE(zi_left,zi_right,zi_down,zi_left_up, zi_left_down,zi_right_up,zi_right_down,zi_mid_in,zi_mid_out,'')) = '' 
)
, link_m_d as (
	SELECT 
		'M-D' as "link", 2 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_down  , '')) <> '' 
	AND TRIM(COALESCE(zi_mid  , '')) <> '' 
	AND TRIM(COALESCE(zi_left,zi_right,zi_up,zi_left_up, zi_left_down,zi_right_up,zi_right_down,zi_mid_in,zi_mid_out,'')) = '' 
)
, link_u_m_d as (
	SELECT 
		'U-M-D' as "link", 3 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_up  , '')) <> '' 
	AND TRIM(COALESCE(zi_mid  , '')) <> '' 
	AND TRIM(COALESCE(zi_down  , '')) <> '' 
	AND TRIM(COALESCE(zi_left,zi_right,zi_left_up, zi_left_down,zi_right_up,zi_right_down,zi_mid_in,zi_mid_out,'')) = '' 
)
, link_m_mi as (
	SELECT 
		'M-Mi' as "link", 2 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_mid_in, '')) <> '' 
	AND TRIM(COALESCE(zi_mid  , '')) <> '' 
	AND TRIM(COALESCE(zi_up, zi_down, zi_left,zi_right,zi_left_up, zi_left_down,zi_right_up,zi_right_down,zi_mid_out,'')) = '' 
)
, link_m_mo as (
	SELECT 
		'M-Mo' as "link", 2 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_mid_out,  '')) <> '' 
	AND TRIM(COALESCE(zi_mid  , '')) <> '' 
	AND TRIM(COALESCE(zi_up, zi_down, zi_left,zi_right,zi_left_up, zi_left_down,zi_right_up,zi_right_down,zi_mid_in,'')) = '' 
)
, link_mi_mo as (
	SELECT 
		'Mi-Mo' as "link", 2 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_mid_out,  '')) <> '' 
	AND TRIM(COALESCE(zi_mid_in   , '')) <> '' 
	AND TRIM(COALESCE(zi_up, zi_down, zi_left,zi_right,zi_left_up, zi_left_down,zi_right_up,zi_right_down,zi_mid,'')) = '' 
)
, link_m_mi_mo as (
	SELECT 
		'M-Mi-Mo' as "link", 3 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_mid,  '')) <> '' 
	AND TRIM(COALESCE(zi_mid_out,  '')) <> '' 
	AND TRIM(COALESCE(zi_mid_in   , '')) <> '' 
	AND TRIM(COALESCE(zi_up, zi_down, zi_left,zi_right,zi_left_up, zi_left_down,zi_right_up,zi_right_down,'')) = '' 
)

, link_u_l_r as (
	SELECT 
		'U-L-R' as "link", 3 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_up,  '')) <> '' 
	AND TRIM(COALESCE(zi_left,  '')) <> '' 
	AND TRIM(COALESCE(zi_right,  '')) <> '' 
	AND TRIM(COALESCE(zi_mid, zi_mid_out,zi_mid_in, zi_down, zi_left_down,zi_right_down,  zi_left_up, zi_right_up,'')) = '' 
)

, link_u_ld_rd as (
	SELECT 
		'U-LD-RD' as "link", 3 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_up,  '')) <> '' 
	AND TRIM(COALESCE(zi_left_down,  '')) <> '' 
	AND TRIM(COALESCE(zi_right_down,  '')) <> '' 
	AND TRIM(COALESCE(zi_mid, zi_mid_out,zi_mid_in, zi_down, zi_left,zi_right,zi_left_up, zi_right_up,'')) = '' 
)

, link_u_m_ld_d_rd as (
	SELECT 
		'U-M-LD-D-RD' as "link", 5 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_up,  '')) <> '' 
	AND TRIM(COALESCE(zi_mid,  '')) <> '' 
	AND TRIM(COALESCE(zi_left_down,  '')) <> '' 
	AND TRIM(COALESCE(zi_down,   '')) <> '' 
	AND TRIM(COALESCE(zi_right_down,  '')) <> '' 
	AND TRIM(COALESCE( zi_mid_out,zi_mid_in, zi_left,zi_right,zi_left_up, zi_right_up,'')) = '' 
)

, link_lu_ru_d as (
	SELECT 
		'LU-RU-D' as "link", 3 as "bodies",  t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_down,  '')) <> '' 
	AND TRIM(COALESCE(zi_left_up,  '')) <> '' 
	AND TRIM(COALESCE(zi_right_up,   '')) <> '' 
	AND TRIM(COALESCE(zi_mid, zi_mid_out,zi_mid_in, zi_up,  zi_left,zi_right, zi_right_down, zi_left_down, '')) = '' 
)

, link_lu_u_ru_d as (
	SELECT 
		'LU-U-RU-D' as "link", 4 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_down,  '')) <> '' 
	AND TRIM(COALESCE(zi_left_up,  '')) <> '' 
	AND TRIM(COALESCE(zi_up,  '')) <> '' 
	AND TRIM(COALESCE(zi_right_up,   '')) <> '' 
	AND TRIM(COALESCE(zi_mid, zi_mid_out,zi_mid_in,  zi_left,zi_right, zi_right_down, zi_left_down, '')) = '' 
)

, link_lu_u_ru_m_d as (
	SELECT 
		'LU-U-RU-M-D' as "link", 5 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_left_up,  '')) <> '' 
	AND TRIM(COALESCE(zi_up,  '')) <> '' 
	AND TRIM(COALESCE(zi_right_up,   '')) <> '' 
	AND TRIM(COALESCE(zi_mid,   '')) <> '' 
	AND TRIM(COALESCE(zi_down,  '')) <> '' 
	AND TRIM(COALESCE(zi_mid_out,zi_mid_in,  zi_left,zi_right, zi_right_down, zi_left_down, '')) = '' 
)


, link_lu_ld_r as (
	SELECT 
		'LU-LD-R' as "link", 3 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_left_up,  '')) <> '' 
	AND TRIM(COALESCE(zi_left_down,   '')) <> '' 
	AND TRIM(COALESCE(zi_right,   '')) <> '' 
	AND TRIM(COALESCE(zi_mid, zi_mid_out,zi_mid_in, zi_up,zi_right_up,   zi_left, zi_right_down, zi_down, '')) = '' 
)

, link_l_ru_rd as (
	SELECT 
		'L-RU-RD' as "link", 3 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_left,   '')) <> '' 
	AND TRIM(COALESCE(zi_right_up,   '')) <> '' 
	AND TRIM(COALESCE(zi_right_down,  '')) <> '' 
	AND TRIM(COALESCE(zi_mid, zi_mid_out,zi_mid_in, zi_up,  zi_right, zi_left_down, zi_left_up,    zi_down, '')) = '' 
)

, link_l_ru_r_rd as (
	SELECT 
		'L-RU-R-RD' as "link", 4 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_left,   '')) <> '' 
	AND TRIM(COALESCE(zi_right_up,   '')) <> '' 
	AND TRIM(COALESCE(zi_right,   '')) <> '' 
	AND TRIM(COALESCE(zi_right_down,  '')) <> '' 
	AND TRIM(COALESCE(zi_mid, zi_mid_out,zi_mid_in, zi_up,   zi_left_down, zi_left_up,    zi_down, '')) = '' 
)


, link_lu_ru_ld_rd as (
	SELECT 
		'LU-RU-LD-RD' as "link", 4 as "bodies",  t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_left_up,  '')) <> '' 
	AND TRIM(COALESCE(zi_right_up,  '')) <> '' 
	AND TRIM(COALESCE(zi_left_down,  '')) <> '' 
	AND TRIM(COALESCE(zi_right_down,  '')) <> '' 
	AND TRIM(COALESCE(zi_up, zi_mid, zi_mid_out,zi_mid_in, zi_down, zi_left,zi_right, '')) = '' 
)
, link_lu_m as (
	SELECT 
		'LU-M' as "link", 2 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_left_up, '')) <> '' 
	AND TRIM(COALESCE(zi_mid  , '')) <> '' 
	AND TRIM(COALESCE(zi_up, zi_down, zi_left,zi_right, zi_mid_in, zi_left_down,zi_right_up,zi_right_down,zi_mid_out,'')) = '' 
)
, link_lu_m_d as (
	SELECT 
		'LU-M-D' as "link", 3 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_left_up, '')) <> '' 
	AND TRIM(COALESCE(zi_mid  , '')) <> '' 
	AND TRIM(COALESCE(zi_down,  '')) <> '' 
	AND TRIM(COALESCE(zi_up, zi_mid, zi_left,zi_right, zi_mid_in, zi_left_down,zi_right_up,zi_right_down,zi_mid_out,'')) = '' 
)

, link_ld_m as (
	SELECT 
		'LD-M' as "link", 2 as "bodies",  t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_left_down,'')) <> '' 
	AND TRIM(COALESCE(zi_mid  , '')) <> '' 
	AND TRIM(COALESCE(zi_up, zi_down, zi_left,zi_right, zi_left_up, zi_mid_in, zi_right_up,zi_right_down,zi_mid_out,'')) = '' 
)

, link_ld_u_m as (
	SELECT 
		'LD-U-M' as "link", 3 as "bodies", t_zi_part.*
	FROM t_zi_part 
	WHERE 1=1
	AND TRIM(COALESCE(zi_left_down,'')) <> '' 
	AND TRIM(COALESCE(zi_up, '')) <> '' 
	AND TRIM(COALESCE(zi_mid  , '')) <> '' 
	AND TRIM(COALESCE( zi_down, zi_left,zi_right, zi_left_up, zi_mid_in, zi_right_up,zi_right_down,zi_mid_out,'')) = '' 
)


, links as (
select * from link_l_r
    UNION
select * from link_l_m
    UNION
select * from link_m_r
    UNION
select * from link_l_m_r



    UNION
select * from link_l_m_r_d
    UNION
select * from link_u_d
    UNION
select * from link_u_m
    UNION
select * from link_m_d
    UNION
select * from link_u_m_d
    UNION
select * from link_m_mi
    UNION
select * from link_m_mo
    UNION
select * from link_mi_mo
    UNION
select * from link_m_mi_mo
    UNION
select * from link_u_l_r
    UNION
select * from link_u_ld_rd
    UNION
select * from link_u_m_ld_d_rd
    UNION
select * from link_lu_ru_d
    UNION
select * from link_lu_u_ru_d  
    UNION
select * from link_lu_u_ru_m_d  

    UNION
select * from link_lu_ld_r
    UNION
select * from link_l_ru_rd
    UNION
select * from link_l_ru_r_rd
    UNION
select * from link_lu_ru_ld_rd
    UNION
select * from link_lu_m
    UNION
select * from link_lu_m_d

    UNION
select * from link_ld_m
    UNION 
select * from     link_ld_u_m
)
-- select * from links;
-- select count(*) from links   -- 5788

select 
    bodies as "Bodies", 
    link as "Comp.Pattern", 
    count(*) as "Frequency" 
from links group by link 
order by bodies, frequency desc;

"""

with DBConn() as _conn:
    df_link = pd.read_sql(sql_link, _conn)  

df_link

    Bodies Comp.Pattern  Frequency
0        2          L-M       3034
1        2          U-D        729
2        2          U-M        691
3        2          L-R        536
4        2          M-R        300
5        2         LD-M        119
6        2         M-Mi        117
7        2         LU-M        106
8        2          M-D         70
9        2         M-Mo         21
10       2        Mi-Mo          6
11       3        U-M-D        139
12       3      LU-RU-D         45
13       3      LU-LD-R         28
14       3        L-M-R         26
15       3      L-RU-RD         20
16       3      U-LD-RD         20
17       3        U-L-R          9
18       3       LD-U-M          3
19       3      M-Mi-Mo          1
20       4    LU-U-RU-D          7
21       4  LU-RU-LD-RD          6
22       4      L-M-R-D          2
23       4    L-RU-R-RD          2
24       5  U-M-LD-D-RD          4
25       5  LU-U-RU-M-D          1